### ISSUE TITLE
JSON problem

### ISSUE THREAD

**Issue by Aminlp** [cybermaggedon/pyvera#6]
Hi
i want to use this api in my third-party program but at start of my work after create LUUP-AUTH.json file, and follow your instruction, the program has some error about json decoding.
this is my LUUP-AUTH file:
```
{
  "local":{
    "address": "LOCAL IP ADDRESS"
  }
}
{
  "remote":
  {
    "user": "USERNAME",
    "password": "PASSWORD",
    "device": "DEVICE_ID"
  }
}
```
and return this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vera.py", line 1924, in __init__
    response = self.session.get(url).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
what should i do?
thanks

**Comment by cybermaggedon** [comment]
Hey there, does your config file contain both a local AND a remote object? That would be a problem, you should have one or the other, not both.

**Comment by Aminlp** [comment]
NO, my config file just contain remote object. but in first step of initialization, i encounter to TOP error.
what should i do?
thanks

**Comment by cybermaggedon** [comment]
Ok, that looks like it failed when trying to decode the JSON coming back from the authentication.

```
        auth_server = "vera-us-oem-autha11.mios.com"

        url = "https://%s/autha/auth/username/%s?SHA1Password=%s&PK_Oem=1" % \
              (auth_server, user.lower(), sha1p)
```

It looks like the result that came back wasn't JSON.

I get a similar error by putting the wrong password in...
```
[pyvera]$ ./get_scenes REMOTE.cfg Heating
Traceback (most recent call last):
  File "./get_scenes", line 11, in <module>
    ve = vera.connect(sys.argv[1])
  File "/home/mark/dev/pyvera/vera.py", line 2032, in connect
    return VeraRemote(user, password, device)
  File "/home/mark/dev/pyvera/vera.py", line 1924, in __init__
    response = self.session.get(url).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by cybermaggedon** [comment]
Maybe check you have the right details in your config file and that the format is right...
```
{
  "remote": {
    "user": "x***********",
    "password": "z*********",
    "device": "123456778"
  }
}
```

**Comment by cybermaggedon** [comment]
I've just fixed a bug in the SHA API which prevented this working, try latest code should be working.
