### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by scaldara55** [cybermaggedon/pyvera#9]
Newbie question.  I like what I see in your repository for interacting with Vera.  I do not know how to install the module.  I don't see a setup.py for installation.  If I pip install vera it doesn't recognize the method to connect to the controller.  If I pip install pyvera I get a different repository.

**Comment by scaldara55** [comment]
I figured it out.  Clone the repository and run it locally.

**Comment by cybermaggedon** [comment]
I added packaging, so something like this should work...
```
pip3 install --user git+https://github.com/cybermaggedon/pyvera
```

**Comment by scaldara55** [comment]
I used your pip3 install command.  I'm running Python 3.9.1.  The import works fine.  When I try to create the local object I get an error.

>>> ve = vera.VeraLocal("192.168.1.127")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steve/.virtualenvs/py3.9.1cv/lib/python3.9/site-packages/vera/vera.py", line 1909, in __init__
    Vera.__init__(self)
  File "/Users/steve/.virtualenvs/py3.9.1cv/lib/python3.9/site-packages/vera/vera.py", line 1509, in __init__
    self.update_state()
  File "/Users/steve/.virtualenvs/py3.9.1cv/lib/python3.9/site-packages/vera/vera.py", line 1582, in update_state
    s.definition = SceneDefinition.parse(self, i)
  File "/Users/steve/.virtualenvs/py3.9.1cv/lib/python3.9/site-packages/vera/vera.py", line 1145, in parse
    for i in s["triggers"]:
KeyError: 'triggers'
>>> 

I took a look at the code and the only thing I saw was that you use 'triggers' both as a name of a list as well as a key in a dictionary.  Could this cause the problem?

**Comment by scaldara55** [comment]
See comment above

**Comment by cybermaggedon** [comment]
@scaldara55 Looks like the  'triggers' object is optional, and i should have been checking for it before using.  I've  pushed a commit, maybe that works?
